title: Cybersecurity Portfolio
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
author: "Lee Ann"
email: "lannn.sg@gmail.com"
description: "A collection of my cybersecurity projects, write-ups, research and insights related to cybersecurity."

# Enable GitHub Pages navigation links
show_downloads: false
baseurl: "/cybersecurity-portfolio" #Set to "" (empty) for root access
url: "https://leeannn01.github.io"


# Enable collections for Projects, Blog, and Write-ups
collections:
  projects:
    output: true
  blog:
    output: true
  writeups:
    output: true

# Navigation Links
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Writeup
    url: /writeup/r
  - title: Contact
    url: /contact/
    
# Markdown Processing
markdown: kramdown
permalink: pretty